### ISSUE TITLE
Looks like an issue with umbraco 8.6.2

### ISSUE THREAD

**Issue by seanrockster** [designagencyuk/DesignAgency.BoboFacets#5]
Could be due to ioc ???

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

Exception Details: Umbraco.Core.Exceptions.BootFailedException: Boot failed: Umbraco cannot run. See Umbraco's log file for more details.

-> Umbraco.Core.Exceptions.BootFailedException: Boot failed.

-> System.Reflection.ReflectionTypeLoadException: Could not load all types from "DesignAgency.BoboFacets, Version=0.1.1.0, Culture=neutral, PublicKeyToken=null" due to LoaderExceptions, skipping:
. System.TypeLoadException on Umbraco.Core.ObjectResolution.ManyObjectsResolverBase`2: Could not load type 'Umbraco.Core.ObjectResolution.ManyObjectsResolverBase`2' from assembly 'Umbraco.Core, Version=8.0.0.0, Culture=neutral, PublicKeyToken=null'.
. System.TypeLoadException on Umbraco.Core.ApplicationEventHandler: Could not load type 'Umbraco.Core.ApplicationEventHandler' from assembly 'Umbraco.Core, Version=8.0.0.0, Culture=neutral, PublicKeyToken=null'.

  at Umbraco.Core.Composing.TypeFinder.GetTypesWithFormattedException(Assembly a) in D:\a\1\s\src\Umbraco.Core\Composing\TypeFinder.cs:line 572
  at Umbraco.Core.Composing.TypeFinder.GetClassesWithBaseType(Type baseType, IEnumerable`1 assemblies, Boolean onlyConcreteClasses, Func`2 additionalFilter) in D:\a\1\s\src\Umbraco.Core\Composing\TypeFinder.cs:line 504
  at Umbraco.Core.Composing.TypeLoader.<>c__DisplayClass53_0`1.<GetTypes>b__1() in D:\a\1\s\src\Umbraco.Core\Composing\TypeLoader.cs:line 586
  at Umbraco.Core.Composing.TypeLoader.GetTypesInternalLocked(Type baseType, Type attributeType, Func`1 finder, String action, Boolean cache) in D:\a\1\s\src\Umbraco.Core\Composing\TypeLoader.cs:line 796
  at Umbraco.Core.Composing.TypeLoader.GetTypesInternal(Type baseType, Type attributeType, Func`1 finder, String action, Boolean cache) in D:\a\1\s\src\Umbraco.Core\Composing\TypeLoader.cs:line 700
  at Umbraco.Core.Composing.TypeLoader.GetTypes[T](Boolean cache, IEnumerable`1 specificAssemblies) in D:\a\1\s\src\Umbraco.Core\Composing\TypeLoader.cs:line 584
  at Umbraco.Core.Runtime.CoreRuntime.ResolveComposerTypes(TypeLoader typeLoader) in D:\a\1\s\src\Umbraco.Core\Runtime\CoreRuntime.cs:line 306
  at Umbraco.Core.Runtime.CoreRuntime.Boot(IRegister register, DisposableTimer timer) in D:\a\1\s\src\Umbraco.Core\Runtime\CoreRuntime.cs:line 172

**Comment by TomSteer** [comment]
The current 0.1.1 release doesn't support v8 of Umbraco. 

I've started a new version for v8 but haven't got around to releasing it yet. You can find the code on the [v8 branch](https://github.com/designagencyuk/DesignAgency.BoboFacets/tree/v8) if you wanted to test it out.

**Comment by TimGeyssens** [comment]
hey @TomSteer any chance you can output a pre release on nuget of that one (the v8 compatible build)? Thanks

**Comment by TomSteer** [comment]
Hi @TimGeyssens I'll try to get a pre-release out this week. I just need to spend a bit of time updating the package build.

**Comment by TimGeyssens** [comment]
@TomSteer sounds great!

**Comment by TomSteer** [comment]
@TimGeyssens I've pushed a v2 pre-release to Nuget now (https://www.nuget.org/packages/DesignAgency.BoboFacets/2.0.0-beta). As I haven't done any Umbraco 8 projects that needed faceted search yet, the only real testing I've done of this version is during the initial port to Umbraco 8, so if you find any issues just let me know 👍.
Also, the best place to see what's changed in terms of the setup/configuration is the example project in the repo (I'll update the docs before I do a final release).

**Comment by TimGeyssens** [comment]
@TomSteer nice, will do, thanks!
